spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/endgame?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 96862171544-b2g8uu1thn93lr7jjqbtdgr64p5nb6e4.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email,profile
          kakao:
            client-id: ff7a36f92d7f8068509f5f39f734c906
            client-secret: ZsK3XsUwDAQ2XivDN5WSvFwoepl1iefQ
            scope: account_email,profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST
          naver:
            client-id: PbT7PycInsXVmzawn_y3
            client-secret: u7J3A4MIya
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  # Toss 설정 추가
payment:
  key:
    secret: "test_sk_DnyRpQWGrNmw2yRYYROVKwv1M9EN:"

carImgLocation: D:/endcar2/item/
uploadPath: file:///D:/endcar2/
